name: Fix coding styles using Laravel Pint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code base
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: laravel pint
        uses: aglipanci/laravel-pint-action@latest
        with:
          configPath: "pint.json"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Linting (Pint)